6.746568"461003639959": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
5.355428"461010230585": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624272361896", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.861241"461000249378": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.308532"461004514444": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624272364076", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.492609"461000249497": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.283213"461004251843": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624272365880", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.451229"461004216817": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624272368322", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.137729"461000052951": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.338823"461002407783": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624272372823", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.837037"461000363036": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
